"""add_essl_connector_tables

Revision ID: 0ff14a92da4a
Revises: 3b6cf98d123b
Create Date: 2026-06-25 04:15:42.139962
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0ff14a92da4a'
down_revision: Union[str, None] = '3b6cf98d123b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essl_servers',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('server_url', sa.String(length=512), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('auto_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('attendance_sync_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('device_sync_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('employee_sync_hour', sa.Integer(), nullable=False),
    sa.Column('employee_conflict_policy', sa.String(length=50), nullable=False),
    sa.Column('device_conflict_policy', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('server_version', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_essl_servers')),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_essl_servers_tenant_name')
    )
    op.create_index(op.f('ix_essl_servers_tenant_id'), 'essl_servers', ['tenant_id'], unique=False)
    op.create_table('essl_sync_cursor',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('essl_server_id', sa.UUID(), nullable=False),
    sa.Column('cursor_type', sa.String(length=50), nullable=False),
    sa.Column('last_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('last_punch_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_employee_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_device_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['essl_server_id'], ['essl_servers.id'], name=op.f('fk_essl_sync_cursor_essl_server_id_essl_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_essl_sync_cursor')),
    sa.UniqueConstraint('essl_server_id', 'cursor_type', name='uq_essl_cursor_server_type')
    )
    op.create_index(op.f('ix_essl_sync_cursor_essl_server_id'), 'essl_sync_cursor', ['essl_server_id'], unique=False)
    op.create_index(op.f('ix_essl_sync_cursor_tenant_id'), 'essl_sync_cursor', ['tenant_id'], unique=False)
    op.create_table('essl_sync_history',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('essl_server_id', sa.UUID(), nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=False),
    sa.Column('date_range_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_range_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['essl_server_id'], ['essl_servers.id'], name=op.f('fk_essl_sync_history_essl_server_id_essl_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_essl_sync_history'))
    )
    op.create_index(op.f('ix_essl_sync_history_essl_server_id'), 'essl_sync_history', ['essl_server_id'], unique=False)
    op.create_index(op.f('ix_essl_sync_history_tenant_id'), 'essl_sync_history', ['tenant_id'], unique=False)
    op.create_table('essl_sync_jobs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('essl_server_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('scheduled_hour', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=50), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['essl_server_id'], ['essl_servers.id'], name=op.f('fk_essl_sync_jobs_essl_server_id_essl_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_essl_sync_jobs')),
    sa.UniqueConstraint('essl_server_id', 'job_type', name='uq_essl_sync_jobs_server_type')
    )
    op.create_index(op.f('ix_essl_sync_jobs_essl_server_id'), 'essl_sync_jobs', ['essl_server_id'], unique=False)
    op.create_index(op.f('ix_essl_sync_jobs_tenant_id'), 'essl_sync_jobs', ['tenant_id'], unique=False)
    op.create_table('essl_sync_errors',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('sync_history_id', sa.UUID(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_identifier', sa.String(length=255), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sync_history_id'], ['essl_sync_history.id'], name=op.f('fk_essl_sync_errors_sync_history_id_essl_sync_history'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_essl_sync_errors'))
    )
    op.create_index(op.f('ix_essl_sync_errors_sync_history_id'), 'essl_sync_errors', ['sync_history_id'], unique=False)
    op.create_index(op.f('ix_essl_sync_errors_tenant_id'), 'essl_sync_errors', ['tenant_id'], unique=False)
    op.create_table('attendance_raw_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('essl_server_id', sa.UUID(), nullable=True),
    sa.Column('employee_code', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('device_serial', sa.String(length=100), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('punch_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('punch_type', sa.String(length=50), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_attendance_raw_logs_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_attendance_raw_logs_employee_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['essl_server_id'], ['essl_servers.id'], name=op.f('fk_attendance_raw_logs_essl_server_id_essl_servers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_attendance_raw_logs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_raw_logs')),
    sa.UniqueConstraint('essl_server_id', 'employee_code', 'punch_time', 'punch_type', name='uq_raw_logs_server_code_time_type')
    )
    op.create_index(op.f('ix_attendance_raw_logs_employee_id'), 'attendance_raw_logs', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_raw_logs_essl_server_id'), 'attendance_raw_logs', ['essl_server_id'], unique=False)
    op.create_index(op.f('ix_attendance_raw_logs_processed'), 'attendance_raw_logs', ['processed'], unique=False)
    op.create_index(op.f('ix_attendance_raw_logs_tenant_id'), 'attendance_raw_logs', ['tenant_id'], unique=False)
    op.create_index('ix_raw_logs_unprocessed', 'attendance_raw_logs', ['tenant_id', 'processed'], unique=False)
    op.create_table('essl_device_mapping',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('essl_server_id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_essl_device_mapping_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['essl_server_id'], ['essl_servers.id'], name=op.f('fk_essl_device_mapping_essl_server_id_essl_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_essl_device_mapping')),
    sa.UniqueConstraint('essl_server_id', 'device_id', name='uq_essl_dev_mapping_server_dev'),
    sa.UniqueConstraint('essl_server_id', 'serial_number', name='uq_essl_dev_mapping_server_serial')
    )
    op.create_index(op.f('ix_essl_device_mapping_essl_server_id'), 'essl_device_mapping', ['essl_server_id'], unique=False)
    op.create_index(op.f('ix_essl_device_mapping_tenant_id'), 'essl_device_mapping', ['tenant_id'], unique=False)
    op.create_table('essl_employee_mapping',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('essl_server_id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_essl_employee_mapping_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['essl_server_id'], ['essl_servers.id'], name=op.f('fk_essl_employee_mapping_essl_server_id_essl_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_essl_employee_mapping')),
    sa.UniqueConstraint('essl_server_id', 'employee_code', name='uq_essl_emp_mapping_server_code'),
    sa.UniqueConstraint('essl_server_id', 'employee_id', name='uq_essl_emp_mapping_server_emp')
    )
    op.create_index(op.f('ix_essl_employee_mapping_essl_server_id'), 'essl_employee_mapping', ['essl_server_id'], unique=False)
    op.create_index(op.f('ix_essl_employee_mapping_tenant_id'), 'essl_employee_mapping', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_essl_employee_mapping_tenant_id'), table_name='essl_employee_mapping')
    op.drop_index(op.f('ix_essl_employee_mapping_essl_server_id'), table_name='essl_employee_mapping')
    op.drop_table('essl_employee_mapping')
    op.drop_index(op.f('ix_essl_device_mapping_tenant_id'), table_name='essl_device_mapping')
    op.drop_index(op.f('ix_essl_device_mapping_essl_server_id'), table_name='essl_device_mapping')
    op.drop_table('essl_device_mapping')
    op.drop_index('ix_raw_logs_unprocessed', table_name='attendance_raw_logs')
    op.drop_index(op.f('ix_attendance_raw_logs_tenant_id'), table_name='attendance_raw_logs')
    op.drop_index(op.f('ix_attendance_raw_logs_processed'), table_name='attendance_raw_logs')
    op.drop_index(op.f('ix_attendance_raw_logs_essl_server_id'), table_name='attendance_raw_logs')
    op.drop_index(op.f('ix_attendance_raw_logs_employee_id'), table_name='attendance_raw_logs')
    op.drop_table('attendance_raw_logs')
    op.drop_index(op.f('ix_essl_sync_errors_tenant_id'), table_name='essl_sync_errors')
    op.drop_index(op.f('ix_essl_sync_errors_sync_history_id'), table_name='essl_sync_errors')
    op.drop_table('essl_sync_errors')
    op.drop_index(op.f('ix_essl_sync_jobs_tenant_id'), table_name='essl_sync_jobs')
    op.drop_index(op.f('ix_essl_sync_jobs_essl_server_id'), table_name='essl_sync_jobs')
    op.drop_table('essl_sync_jobs')
    op.drop_index(op.f('ix_essl_sync_history_tenant_id'), table_name='essl_sync_history')
    op.drop_index(op.f('ix_essl_sync_history_essl_server_id'), table_name='essl_sync_history')
    op.drop_table('essl_sync_history')
    op.drop_index(op.f('ix_essl_sync_cursor_tenant_id'), table_name='essl_sync_cursor')
    op.drop_index(op.f('ix_essl_sync_cursor_essl_server_id'), table_name='essl_sync_cursor')
    op.drop_table('essl_sync_cursor')
    op.drop_index(op.f('ix_essl_servers_tenant_id'), table_name='essl_servers')
    op.drop_table('essl_servers')
    # ### end Alembic commands ###
