"""add_dedup_index

Revision ID: 34d53d38e2ec
Revises: ba139397b281
Create Date: 2026-06-25 04:47:00.862962
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '34d53d38e2ec'
down_revision: Union[str, None] = 'ba139397b281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_raw_logs_tenant_code_time_type', 'attendance_raw_logs', type_='unique')
    op.create_index('ix_raw_logs_dedup_check', 'attendance_raw_logs', ['tenant_id', 'employee_code', 'punch_time'], unique=False)
    op.create_unique_constraint('uq_raw_logs_server_code_time_type', 'attendance_raw_logs', ['essl_server_id', 'employee_code', 'punch_time', 'punch_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_raw_logs_server_code_time_type', 'attendance_raw_logs', type_='unique')
    op.drop_index('ix_raw_logs_dedup_check', table_name='attendance_raw_logs')
    op.create_unique_constraint('uq_raw_logs_tenant_code_time_type', 'attendance_raw_logs', ['tenant_id', 'employee_code', 'punch_time', 'punch_type'])
    # ### end Alembic commands ###
