"""add_sync_progress_fields

Revision ID: a6dacfc268bc
Revises: caaacd017b3e
Create Date: 2026-06-25 04:34:49.902038
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a6dacfc268bc'
down_revision: Union[str, None] = 'caaacd017b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('essl_sync_history', sa.Column('progress_percent', sa.Integer(), nullable=False))
    op.add_column('essl_sync_history', sa.Column('total_records_expected', sa.Integer(), nullable=True))
    op.add_column('essl_sync_history', sa.Column('current_batch', sa.Integer(), nullable=True))
    op.add_column('essl_sync_history', sa.Column('total_batches', sa.Integer(), nullable=True))
    op.add_column('essl_sync_history', sa.Column('is_paused', sa.Boolean(), nullable=False))
    op.add_column('essl_sync_history', sa.Column('is_cancelled', sa.Boolean(), nullable=False))
    op.add_column('essl_sync_history', sa.Column('last_checkpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('essl_sync_history', 'last_checkpoint')
    op.drop_column('essl_sync_history', 'is_cancelled')
    op.drop_column('essl_sync_history', 'is_paused')
    op.drop_column('essl_sync_history', 'total_batches')
    op.drop_column('essl_sync_history', 'current_batch')
    op.drop_column('essl_sync_history', 'total_records_expected')
    op.drop_column('essl_sync_history', 'progress_percent')
    # ### end Alembic commands ###
