"""fix_raw_logs_dedup_constraint

Revision ID: ba139397b281
Revises: a6dacfc268bc
Create Date: 2026-06-25 04:41:53.554289
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ba139397b281'
down_revision: Union[str, None] = 'a6dacfc268bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_raw_logs_server_code_time_type', 'attendance_raw_logs', type_='unique')
    op.create_unique_constraint('uq_raw_logs_tenant_code_time_type', 'attendance_raw_logs', ['tenant_id', 'employee_code', 'punch_time', 'punch_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_raw_logs_tenant_code_time_type', 'attendance_raw_logs', type_='unique')
    op.create_unique_constraint('uq_raw_logs_server_code_time_type', 'attendance_raw_logs', ['essl_server_id', 'employee_code', 'punch_time', 'punch_type'])
    # ### end Alembic commands ###
