"""fix_essl_tenant_fks

Revision ID: caaacd017b3e
Revises: 0ff14a92da4a
Create Date: 2026-06-25 04:26:50.019016
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'caaacd017b3e'
down_revision: Union[str, None] = '0ff14a92da4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_essl_device_mapping_tenant_id_tenants'), 'essl_device_mapping', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_essl_employee_mapping_tenant_id_tenants'), 'essl_employee_mapping', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_essl_servers_tenant_id_tenants'), 'essl_servers', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_essl_sync_cursor_tenant_id_tenants'), 'essl_sync_cursor', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_essl_sync_errors_tenant_id_tenants'), 'essl_sync_errors', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_essl_sync_history_tenant_id_tenants'), 'essl_sync_history', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_essl_sync_jobs_tenant_id_tenants'), 'essl_sync_jobs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_essl_sync_jobs_tenant_id_tenants'), 'essl_sync_jobs', type_='foreignkey')
    op.drop_constraint(op.f('fk_essl_sync_history_tenant_id_tenants'), 'essl_sync_history', type_='foreignkey')
    op.drop_constraint(op.f('fk_essl_sync_errors_tenant_id_tenants'), 'essl_sync_errors', type_='foreignkey')
    op.drop_constraint(op.f('fk_essl_sync_cursor_tenant_id_tenants'), 'essl_sync_cursor', type_='foreignkey')
    op.drop_constraint(op.f('fk_essl_servers_tenant_id_tenants'), 'essl_servers', type_='foreignkey')
    op.drop_constraint(op.f('fk_essl_employee_mapping_tenant_id_tenants'), 'essl_employee_mapping', type_='foreignkey')
    op.drop_constraint(op.f('fk_essl_device_mapping_tenant_id_tenants'), 'essl_device_mapping', type_='foreignkey')
    # ### end Alembic commands ###
